(function($,window,undefined){$.fn.getDFPads=function(options){var defaults=$.extend({dfp_instance:'43340684',dfp_id:'data-dfp-id',dfp_sizes:'data-dfp-sizes',dfp_ad_targeting:'data-dfp-targeting',dfp_outofpage:'data-dfp-outofpage',dfp_collapse:'data-dfp-collapse',dfp_responsive:'data-dfp-responsive',dfp_refresh:'data-dfp-refresh',custom_variables:'',size_mappings:'',piiCheck:false,lazyload_selector:'.lazyload',lazyload_spacer:800,collapsible_selector:'.collapsible',showNonPersonalisedAds:'false',callback:function(){}},options);var ads=$(this).filter(':visible');var get_ads=false;var is_dev=false;var openx_json=defaults.openx_json;var zones=[];var zone_groups=[];var tags=[];var rendered=0;var ads_overlay=$('<div />',{id:'ads_status_overlay',}).css({position:'fixed',top:'20px',right:'20px',padding:'20px',background:'#8dd87a','z-index':'100000','text-align':'left','font-family':'Arial, sans-serif','font-size':'14px','height':'600px','overflow-y':'scroll'});getDimensions=function($adUnit){var dimensions=[],dimensionsData=$adUnit.attr(defaults.dfp_sizes);if(dimensionsData){var dimensionGroups=dimensionsData.split(',');$.each(dimensionGroups,function(k,v){var dimensionSet=v.split('x');dimensions.push([parseInt(dimensionSet[0],10),parseInt(dimensionSet[1],10)]);});}else{dimensions.push([$adUnit.width(),$adUnit.height()]);}
return dimensions;},loadDFP=function(){window.googletag=window.googletag||{};window.googletag.cmd=window.googletag.cmd||[];var gads=document.createElement('script');gads.async=true;gads.type='text/javascript';var useSSL='https:'===document.location.protocol;gads.src=(useSSL?'https:':'http:')+'//www.googletagservices.com/tag/js/gpt.js';var node=document.getElementsByTagName('script')[0];node.parentNode.insertBefore(gads,node);},urlToArray=function(url){var request={};var pairs=url.substring(url.indexOf('?')+1).split('&');for(var i=0;i<pairs.length;i++){if(!pairs[i])
continue;var pair=pairs[i].split('=');request[decodeURIComponent(pair[0])]=decodeURIComponent(pair[1]);}
return request;},isEmail=function(email){var regex=/^([a-zA-Z0-9_.+-])+\@(([a-zA-Z0-9-])+\.)+([a-zA-Z0-9]{2,4})+$/;return regex.test(email);},isDev=function(){is_dev=true;var ads_overlay_title=$('<h2 />',{html:'Ads Status:',}).css({padding:'0 0 10px 0','border-bottom':'1px dotted white',margin:'0 0 10px 0',});ads_overlay.append(ads_overlay_title);$('body').append(ads_overlay);var ads_overlay_div=$('<div />').css({padding:'0 0 10px 0','border-bottom':'1px dotted white',margin:'0 0 10px 0',});ads_overlay_div.append('<h3>Non-Personalised Ads: </h3><p>'+defaults.showNonPersonalisedAds+'</p>');ads_overlay_div.append('<h3>Page Targeting: </h3><p>url (40 characters): '+window.location.pathname.substring(0,40)+'</p>');if(defaults.custom_variables){$.each(defaults.custom_variables,function(key,val){ads_overlay_div.append('<p>'+key+': '+val+'</p>');});}
ads_overlay.append(ads_overlay_div);},logAd=function(ad){var ads_overlay_div=$('<div />').css({padding:'0 0 10px 0','border-bottom':'1px dotted white',margin:'0 0 10px 0',});ads_overlay_div.append('<h3>Requesting Ad Unit: '+$(ad).attr(defaults.dfp_id)+'</h3>');ads_overlay_div.append('<p>'+$(ad).attr('id')+'</p>');ads_overlay_div.append('<p>Sizes: '+$(ad).attr(defaults.dfp_sizes)+'</p>');if($(ad).attr(defaults.dfp_ad_targeting)){ads_overlay_div.append('<p>Targeting: '+$(ad).attr(defaults.dfp_ad_targeting)+'</p>');}
ads_overlay.append(ads_overlay_div);},createAds=function(theseAds){var zones=[];var slots=[];$(theseAds).each(function(){if($(this).css('display')=='block'||$(this).css('display').indexOf('box')>=0){var dfpId=$(this).attr(defaults.dfp_id);var zoneId=$(this).attr('id');var refresh='';if($(this).attr(defaults.dfp_sizes)=='fluid'){var dimensions='fluid';}else{var dimensions=getDimensions($(this));}
var ad_targeting=$(this).attr(defaults.dfp_ad_targeting);var outofpage=$(this).attr(defaults.dfp_outofpage);var collapse=$(this).attr(defaults.dfp_collapse);var responsive=$(this).attr(defaults.dfp_responsive);var refresh=$(this).attr(defaults.dfp_refresh);zones.push(zoneId);if(is_dev){logAd($(this));}
window.googletag.cmd.push(function(){if(outofpage){slots[zoneId]=window.googletag.defineOutOfPageSlot('/'+defaults.dfp_instance+'/'+dfpId,zoneId).addService(window.googletag.pubads());}else{slots[zoneId]=window.googletag.defineSlot('/'+defaults.dfp_instance+'/'+dfpId,dimensions,zoneId).addService(window.googletag.pubads());}
if(ad_targeting){var targeting=[];var targetingGroups=ad_targeting.split(',');$.each(targetingGroups,function(k,v){var targetingSet=v.split('=');slots[zoneId].setTargeting(targetingSet[0],targetingSet[1]);});}
if(collapse=="true"){slots[zoneId].setCollapseEmptyDiv(true);}
if(responsive&&defaults.size_mappings[responsive]){var map=googletag.sizeMapping();$.each(defaults.size_mappings[responsive],function(k,v){map.addSize(v.viewport,v.ad_sizes);});slots[zoneId].defineSizeMapping(map.build());}
if(refresh){var refresh_timeout=parseInt(refresh)*1000;setInterval(function(){var ads_overlay_div=$('<div />').css({padding:'0 0 10px 0','border-bottom':'1px dotted white',margin:'0 0 10px 0',});ads_overlay_div.append('<h3>Refreshing Ad Unit: '+dfpId+'</h3>');ads_overlay.append(ads_overlay_div);googletag.pubads().refresh([slots[zoneId]]);},refresh_timeout);}});};});window.googletag.cmd.push(function(){window.googletag.pubads().enableSingleRequest();checkNonPersonalisedAds();if(defaults.custom_variables){$.each(defaults.custom_variables,function(key,val){window.googletag.pubads().setTargeting(key,val);});}
if(!defaults.custom_variables['url']){window.googletag.pubads().setTargeting('url',window.location.pathname.substring(0,40));}
window.googletag.pubads().addEventListener('slotRenderEnded',function(event){rendered++;if(event.isEmpty){$('#'+event.slot.getSlotElementId()).parent(defaults.collapsible_selector).hide();$('#'+event.slot.getSlotElementId()).parent().parent(defaults.collapsible_selector).hide();$('#'+event.slot.getSlotElementId()).parent().parent().parent(defaults.collapsible_selector).hide();}});window.googletag.enableServices();});displayAds(zones);},checkNonPersonalisedAds=function(){if(defaults.showNonPersonalisedAds=='true'){window.googletag.pubads().setRequestNonPersonalizedAds(1);}else{window.googletag.pubads().setRequestNonPersonalizedAds(0);}
window.googletag.pubads().setTargeting('npa',defaults.showNonPersonalisedAds);}
displayAds=function(zones){$.each(zones,function(key,val){window.googletag.cmd.push(function(){window.googletag.display(val);});});defaults.callback.call(this);},lazyloadAds=function(){lazyload_ads=$(defaults.lazyload_selector);if(lazyload_ads.length>0){for(i=0;i<lazyload_ads.length;i++){var lazyload_ad=lazyload_ads[i];if(isInViewport(lazyload_ad,defaults.lazyload_spacer)){requestAd(lazyload_ad);$(lazyload_ad).removeClass('lazyload').addClass('lazyloaded');}}}},isInViewport=function(ad,buffer){var elementTop=$(ad).offset().top;var elementBottom=elementTop+$(ad).outerHeight();var viewportTop=$(window).scrollTop();var viewportBottom=viewportTop+$(window).height()+buffer;return elementBottom>viewportTop&&elementTop<viewportBottom;},requestAd=function(ad){if(typeof $(ad).attr(defaults.dfp_sizes)!==typeof undefined&&$(ad).attr(defaults.dfp_sizes)!==false){var sizes=$(ad).attr(defaults.dfp_sizes).split(',');for(k=0;k<sizes.length;k++){sizes[k]=sizes[k].split('x').map(Number);}
sizes=sizes.length==1?sizes[0]:sizes;}else{return;}
var targeting='';if(typeof $(ad).attr(defaults.dfp_ad_targeting)!==typeof undefined&&$(ad).attr(defaults.dfp_ad_targeting)!==false){var targeting=$(ad).attr(defaults.dfp_ad_targeting).split(',');}
var collapse='';if(typeof $(ad).attr(defaults.dfp_collapse)!==typeof undefined&&$(ad).attr(defaults.dfp_collapse)!==false){var collapse=$(ad).attr(defaults.dfp_collapse);}
if(is_dev){logAd($(ad));}
window.googletag.cmd.push(function(){lazyloadSlot=window.googletag.defineSlot('/43340684/'+$(ad).attr(defaults.dfp_id),sizes,$(ad).attr('id')).addService(window.googletag.pubads());if(targeting){for(k=0;k<targeting.length;k++){rule=targeting[k].split('=');key=rule[0];value=rule[1];lazyloadSlot.setTargeting(key,value);}}
if(collapse){lazyloadSlot.setCollapseEmptyDiv(true);}
checkNonPersonalisedAds();window.googletag.pubads().refresh([lazyloadSlot]);});},loadDFP();urlArray=urlToArray(window.location.search);$.each(urlArray,function(k,v){if(isEmail(v)){defaults.piiCheck=true;}
if(v=='ads_check'){isDev();}});if(!defaults.piiCheck){createAds(ads);var lazyloadInterval=setInterval(lazyloadAds,300);}}})(window.jQuery,window);;(function(window){var IsAB=function(options){this._options={checkOnLoad:false,resetOnEnd:false,loopCheckTime:50,loopMaxNumber:5,baitClass:'pub_300x250 pub_300x250m pub_728x90 text-ad textAd text_ad text_ads text-ads text-ad-links',baitStyle:'width: 1px !important; height: 1px !important; position: absolute !important; left: -10000px !important; top: -1000px !important;',debug:false};this._var={version:'3.2.1',bait:null,checking:false,loop:null,loopNumber:0,event:{detected:[],notDetected:[]}};if(options!==undefined){this.setOption(options);}
var self=this;var eventCallback=function(){setTimeout(function(){if(self._options.checkOnLoad===true){if(self._options.debug===true){self._log('onload->eventCallback','A check loading is launched');}
if(self._var.bait===null){self._creatBait();}
setTimeout(function(){self.check();},1);}},1);};if(window.addEventListener!==undefined){window.addEventListener('load',eventCallback,false);}else{window.attachEvent('onload',eventCallback);}};IsAB.prototype._options=null;IsAB.prototype._var=null;IsAB.prototype._bait=null;IsAB.prototype._log=function(method,message){console.log('[IsAB]['+method+'] '+message);};IsAB.prototype.setOption=function(options,value){if(value!==undefined){var key=options;options={};options[key]=value;}
for(var option in options){this._options[option]=options[option];if(this._options.debug===true){this._log('setOption','The option "'+option+'" he was assigned to "'+options[option]+'"');}}
return this;};IsAB.prototype._creatBait=function(){var bait=document.createElement('div');bait.setAttribute('class',this._options.baitClass);bait.setAttribute('style',this._options.baitStyle);this._var.bait=window.document.body.appendChild(bait);this._var.bait.offsetParent;this._var.bait.offsetHeight;this._var.bait.offsetLeft;this._var.bait.offsetTop;this._var.bait.offsetWidth;this._var.bait.clientHeight;this._var.bait.clientWidth;if(this._options.debug===true){this._log('_creatBait','Bait has been created');}};IsAB.prototype._destroyBait=function(){window.document.body.removeChild(this._var.bait);this._var.bait=null;if(this._options.debug===true){this._log('_destroyBait','Bait has been removed');}};IsAB.prototype.check=function(loop){if(loop===undefined){loop=true;}
if(this._options.debug===true){this._log('check','An audit was requested '+(loop===true?'with a':'without')+' loop');}
if(this._var.checking===true){if(this._options.debug===true){this._log('check','A check was canceled because there is already an ongoing');}
return false;}
this._var.checking=true;if(this._var.bait===null){this._creatBait();}
var self=this;this._var.loopNumber=0;if(loop===true){this._var.loop=setInterval(function(){self._checkBait(loop);},this._options.loopCheckTime);}
setTimeout(function(){self._checkBait(loop);},1);if(this._options.debug===true){this._log('check','A check is in progress ...');}
return true;};IsAB.prototype._checkBait=function(loop){var detected=false;if(this._var.bait===null){this._creatBait();}
if(window.document.body.getAttribute('abp')!==null||this._var.bait.offsetParent===null||this._var.bait.offsetHeight==0||this._var.bait.offsetLeft==0||this._var.bait.offsetTop==0||this._var.bait.offsetWidth==0||this._var.bait.clientHeight==0||this._var.bait.clientWidth==0){detected=true;}
if(window.getComputedStyle!==undefined){var baitTemp=window.getComputedStyle(this._var.bait,null);if(baitTemp&&(baitTemp.getPropertyValue('display')=='none'||baitTemp.getPropertyValue('visibility')=='hidden')){detected=true;}}
if(this._options.debug===true){this._log('_checkBait','A check ('+(this._var.loopNumber+1)+'/'+this._options.loopMaxNumber+' ~'+(1+this._var.loopNumber*this._options.loopCheckTime)+'ms) was conducted and detection is '+(detected===true?'positive':'negative'));}
if(loop===true){this._var.loopNumber++;if(this._var.loopNumber>=this._options.loopMaxNumber){this._stopLoop();}}
if(detected===true){this._stopLoop();this._destroyBait();this.emitEvent(true);if(loop===true){this._var.checking=false;}}else if(this._var.loop===null||loop===false){this._destroyBait();this.emitEvent(false);if(loop===true){this._var.checking=false;}}};IsAB.prototype._stopLoop=function(detected){clearInterval(this._var.loop);this._var.loop=null;this._var.loopNumber=0;if(this._options.debug===true){this._log('_stopLoop','A loop has been stopped');}};IsAB.prototype.emitEvent=function(detected){if(this._options.debug===true){this._log('emitEvent','An event with a '+(detected===true?'positive':'negative')+' detection was called');}
var fns=this._var.event[(detected===true?'detected':'notDetected')];for(var i in fns){if(this._options.debug===true){this._log('emitEvent','Call function '+(parseInt(i)+1)+'/'+fns.length);}
if(fns.hasOwnProperty(i)){fns[i]();}}
if(this._options.resetOnEnd===true){this.clearEvent();}
return this;};IsAB.prototype.clearEvent=function(){this._var.event.detected=[];this._var.event.notDetected=[];if(this._options.debug===true){this._log('clearEvent','The event list has been cleared');}};IsAB.prototype.on=function(detected,fn){this._var.event[(detected===true?'detected':'notDetected')].push(fn);if(this._options.debug===true){this._log('on','A type of event "'+(detected===true?'detected':'notDetected')+'" was added');}
return this;};IsAB.prototype.onDetected=function(fn){return this.on(true,fn);};IsAB.prototype.onNotDetected=function(fn){return this.on(false,fn);};window.IsAB=IsAB;if(window.isAB===undefined){window.isAB=new IsAB({checkOnLoad:true,resetOnEnd:true});}})(window);